### ISSUE TITLE
Support PYPI_BROWSER_PYPI_URL for pypi-server using /simple as endpoint or any self-host pypi server recommand

### ISSUE THREAD

**Issue by ziyi-bear** [chriskuehl/pypi-browser#6]
hi

  we have some pip package for self host test, current using pypi-server to serve
  but facing some issue because pypi-server only using /simple as endpoint

  Is there any solution for pypi-server to work out, or recommand other self-host pypi server is compaitble with this project?

  thanks

**Comment by chriskuehl** [comment]
At the moment there isn't support for using the /simple index, although I think it wouldn't be too hard to add.

Currently pypi-browser relies on [the JSON API provided by Warehouse](https://warehouse.pypa.io/api-reference/json.html) (and also by some other PyPI servers like pypicloud and dumb-pypi).

I wanted to switch it to use the new JSON API in [PEP691](https://peps.python.org/pep-0691/), but it looks like pypiserver doesn't support that yet either (https://github.com/pypiserver/pypiserver/issues/508).

I can try to add support for the `/simple` HTML index some time in the next few days so that it would work with pypiserver.

**Comment by chriskuehl** [comment]
Done in v0.0.9. I've tested it against an Artifactory instance, but please let me know if you run into any issues with pypiserver.
